name: Create and publish a release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ncipollo/release-action@v1
        with:
          name: Release ${{ github.ref }}
          makeLatest: true
  
  publish_to_pypi:
    name: Publish to PyPI
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build and publish to PyPI
        uses: JRubics/poetry-publish@v1.17
        with:
          repository_name: "test-pypi"
          repository_url: "https://test.pypi.org/legacy/"
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          ignore_dev_requirements: "yes"